### ISSUE TITLE
Rails 5 Deprecation warning - before_filter

### ISSUE THREAD

**Issue by shadowed87** [informantapp/informant-rails#3]
I don't know if this is the case with the development version, but after upgrading to Rails 5 I am receiving the following deprecation warning:

`
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from block in <module:RequestTracking> at /usr/lib/ruby/gems/2.3.0/gems/informant-rails-0.9.0/lib/informant-rails/request_tracking.rb:6)
`

**Comment by paulelliott** [comment]
Thanks for reporting this. Version 0.9.1 is now available with the fix.
